### PR TITLE
Fixed mingw compilation

### PR DESCRIPTION
**Pull request by phdussud**
Hello! 
I have been working on a very few changes to fix the mingw compilation. I am totally lost in the structure of this repo because it references some branchless .git file. I haven't figured out how to include the source code changes in this PR. 
The only interesting file change here is the CMakeLists.txt which adds WIN32 and _WIN32 as defined macros for mingw. I found that some mingw distros do add those but some (msys-2) seem to omit these definitions. 
The other changes are very few, they change #ifdef WIN32 to #ifdef _MSC_VER when it covers things that is only for the MS compiler 
/include/sheitmann/libargtable2.h :33
for libwrap private.h:21
and lastly in include: common.h:24 and common.h:35

I believe there are also some missing includes:
src/getopt.c seems to be missing these includes to make mingw happy:
#include <stdlib.h>
#include <string.h>

### CODE REVIEW

**Comment by phdussud** [comment]
I checked in build.sh by mistake. I had to change it locally to specify the tool chain to use because CMAKE always prefer the MS compiler to mingw.... Sorry about that. 
Patrick

**Comment by makestuff** [comment]
Hi Patrick, thanks for your contribution!

As you figured out, this is just the top-level repo which pulls together the libfpgalink repo and all its dependencies, into one big CMake project. It's a bit experimental - I only recently moved this project away from a proprietary build system based on pure makefiles and some scripting & downloading magic, in favour of CMake and git submodules.

So, a change like this necessarily touches several different repos. I don't have a suitable Windows machine available to test this (for MSVC I rely on the CI to identify problems), so ideally you'll need to do it, raising PRs against the affected submodule repos first, and then this repo. You will need to fork [libargtable2](https://github.com/makestuff/libargtable2) and then do something like this:

    cd /c/workspace  # or wherever
    git clone --recursive https://github.com/phdussud/fpgalink.git
    cd fpgalink
    rm -rf libargtable2  # replace the libargtable submodule with your own fork
    git clone https://github.com/phdussud/libargtable2

Now you'll be able to make changes in the `libargtable2` subdirectory, test the top-level build, then commit the libargtable2 changes, push them, and raise a PR against my libargtable2 repo. I will merge it. At that point, you'll see something like this at the top level:

    $ cd /c/workspace  # or wherever
    $ cd fpgalink
    $ git diff .
    diff --git a/libargtable2 b/libargtable2
    index e127736..a666262 160000
    --- a/libargtable2
    +++ b/libargtable2
    @@ -1 +1 @@
    -Subproject commit e127736deb9cce7aa41b4cbf53a5ac530c77f548
    +Subproject commit a666262a5a38562136bc57646eddef70352db364
    $ 

That diff represents the changes you made to the libargtable2 repo, so at that point you can add that change to this PR.

One thing I'd like you to change in this PR is the conditional: I'd prefer a single `if...elseif...else` block for the compiler config, something like this:

    if(MSVC)
      add_compile_options(/W4 /WX /DBYTE_ORDER=1234 /D_CRT_SECURE_NO_WARNINGS)
    elseif (MINGW)
      add_compile_options(-Wall -Wextra -pedantic -Werror -DBYTE_ORDER=1234 -DWIN32 -D_WIN32)
    else()
      add_compile_options(-Wall -Wextra -pedantic -Werror -DBYTE_ORDER=1234)
    endif()

Lastly, perhaps `build.sh` could have a conditional on the platform to decide whether to use the MinGW generator? Something like:

    if [ "$OS" = "Windows_NT" ]; then
      GENERATOR="MinGW Makefiles"
    else
      GENERATOR="Unix Makefiles"
    fi
    :
    cmake \
      -G ${GENERATOR} \
      -DCMAKE_BUILD_TYPE=${CONFIG} \
    :
    
...?

Chris

**Comment by phdussud** [comment]
I modified CMakeLists.txt per your comment. 
Let's not worry about build.sh as people may still want to use MSVC as their compiler. It isn't necessary to make build.sh more complex. As it is, it is very clear and people should be able to modify it locally to their needs. 
I will address the header files changes as you suggest when I have some time to work in it. I will do so in another PR. Please integrate this one. 
Thanks, 
Patrick

**Comment by makestuff** [comment]
So if I have MinGW installed, can I just run `build.sh`? I'm confused about why it would break MSVC users - it you're using MSVC, you will be using `build.cmd`, not `build.sh`. It would be bad if building for MinGW required modifications to `build.sh`.

**Comment by phdussud** [comment]
If MSVC is installed along with MinGW it seems that CMake will use MSVC. So you have to force the use of MinGW by adding the 
-G "MinGW Makefiles" argument to the cmake call in build.sh

**Comment by phdussud** [comment]
I see what you mean about cmd versus .sh. It should be made clear in the README because personally I sometimes use shell scripts with MSVC or cmd files with MinGW.

**Comment by makestuff** [comment]
OK I'll have a think about it. In any case, thanks for your contribution!

**Comment by phdussud** [comment]
Sure!
Another thing.... It seems that the firmware files don't really work as checked in. The code misses a remap address for TDO, so the last byte received is always gotten from the PD0 pin. I re generated them and mine work. However I can't do extensive testing as I have limited hardware. Do you want me to create a PR?
Thanks,
Patrick
________________________________

**Comment by makestuff** [comment]
Gah. This is all pretty old code, and I only recently made it build on a recent sdcc. I tested it on the boards I have available, and it works. But perhaps I only tried on boards where TDO is on PD0. If you have a fix, please do raise a PR, I'll test it more carefully.

**Comment by phdussud** [comment]
Here is the thing... Earlier I got hold of a different SDCC build (don't remember the provenance) and it worked. Now with the official distro (as indicated by the .git you use for fx2lib, the program fails again. This is because the test for _TDO may compile to 2 instructions and the compiler randomly picks one or the other. The lst parser needs to be adjusted  to recognize 30 B0 0B or 30 B0 0C
Just to make sure, this parsing code seems to work:
m = re.search(r"^\s+([0-9A-F]+)\s+(A2|30) B0 (  |0C|0B)\s+(\[\d+\]\s+)?\d+[^;]+_TDO.*?$", line)
Is this correct?
Thanks
________________________________

**Comment by makestuff** [comment]
I'll need to check that. It may take me a couple of days to dig out my collection of FX2-based boards. Thanks for raising it.

**Comment by phdussud** [comment]
Do you want me to raise a PR or do you take it from here?
Take care,
Patrick
________________________________

**Comment by phdussud** [comment]
the fix seems to work but I don't want to me this part more brittle than it is already
________________________________

**Comment by phdussud** [comment]
Thinking about this stuff. it seems to me that all the output pins (TDI, TMS, TCK)  can possibly use the same instructions, so the regexp should be the same except for the default address of the pin.
TDO is input pin so it should be treated differently.
________________________________

**Comment by phdussud** [comment]
OK, I looked at this page for a 8051 instruction reference: 8051 Instruction Set Manual: Opcodes (keil.com)<https://www.keil.com/support/man/docs/is51/is51_opcodes.htm>
I searched for every instructions dealing with bits. Some take bit as input, some as destination.
The ones used for input can  be used with TDO the other ones can be used with TDI, TMS, TCK.
All instructions are 2 bytes except for the  jumps that take an offset, which can be any byte value.
This leads to the following regexps:
m = re.search(r"^\s+([0-9A-F]+)\s+(72|82|A0|A2|10|20|30) B0 (  |[0-9A-F]+)\s+(\[\d+\]\s+)?\d+[^;]+_TDO.*?$", line)
m = re.search(r"^\s+([0-9A-F]+)\s+[9BCD]2 B1\s+(\[\d+\]\s+)?\d+[^;]+_TDI.*?$", line)
m = re.search(r"^\s+([0-9A-F]+)\s+[9BCD]2 B2\s+(\[\d+\]\s+)?\d+[^;]+_TMS.*?$", line)
m = re.search(r"^\s+([0-9A-F]+)\s+[9BCD]2 B3\s+(\[\d+\]\s+)?\d+[^;]+_TCK.*?$", line)

I think these expression will make the decoder much more resilient to program changes. In particular, the jump offset was assumed to be a constant 0B but It changes to 0C with the version of SDCC that we are using now.
This leaves _IOA very fragile but this is a special case anyway.
What do you think?

________________________________

**Pull request merged**
